services:
  postgres:
    image: postgres:16
    container_name: nodesocial_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nodesocial
      POSTGRES_PASSWORD: nodesocialpwd
      POSTGRES_DB: nodesocial_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nodesocial_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch
    container_name: nodesocial_meili
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  pgdata:
  meili_data:
